<?php

namespace SYM16\SimpleStockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{

	//renvoie le nombre total de lignes de l'entité (utilise DQL)
	public function getNbUtilisateur()
	{
		$query = $this ->_em->createQuery('
			SELECT COUNT(u)
			FROM SYM16SimpleStockBundle:Utilisateur u');
		return $query->getSingleScalarResult();
	}

	// même que précédent mais avec Query Builder
	public function getNbUtilisateurWithQueryBuilder()
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('count(u)')->from('SYM16SimpleStockBundle:Utilisateur', 'u');
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getSingleScalarResult();
	}

	//renvoie le nombre total de lignes de l'entité ayant une id données (utilise DQL)
	public function getNbUtilisateurById($id)
	{
		$query = $this ->_em->createQuery('
			SELECT COUNT(u)
			FROM SYM16SimpleStockBundle:Utilisateur u
			WHERE u.droit = :id');
		$query->setParameter('id', $id);
		return $query->getSingleScalarResult();
	}

	// même que précédent mais avec Query Builder
	public function getNbUtilisateurByIdWithQueryBuilder($id)
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('count(u)')->from('SYM16SimpleStockBundle:Utilisateur', 'u');
		$querybuilder->where('u.droit = :id')->setParameter('id', $id);
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getSingleScalarResult();
	}

	// renvoie une entité utilisateur ne contenant que les utilisateurs ayant statut donné
	public function getUtilisateurByStatut($statut)
	{
		$query = $this ->_em->createQuery('
			SELECT u, d
			FROM SYM16SimpleStockBundle:Utilisateur u
			JOIN u.droit d WHERE d.privilege = :statut');
		$query->setParameter('statut', $statut);
		return $query->getResult();
	}

	// même que précédent mais avec Query Builder
	public function getNbUtilisateurByStatutWithQueryBuilder($statut)
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('u')->from('SYM16SimpleStockBundle:Utilisateur', 'u');
		//$querybuilder->leftJoin('u.droit', 'd')->addSelect('d');
		$querybuilder->leftJoin('u.droit', 'd');
		$querybuilder->where('d.privilege = :statut')->setParameter('statut', $statut);
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getResult();
	}

}
