<?php

namespace SYM16\SimpleStockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PetitesFournituresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitesFournituresRepository extends EntityRepository
{
}
