<?php

namespace SYM16\SimpleStockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitRepository extends EntityRepository
{
	//renvoie le nombre total de lignes de l'entité (utilise DQL)
	public function getNbDroit()
	{
		$query = $this ->_em->createQuery('
			SELECT COUNT(d)
			FROM SYM16SimpleStockBundle:Droit d');
		return $query->getSingleScalarResult();
	}

}
