<?php

namespace SYM16\SimpleStockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends EntityRepository
{
	// même que précédent mais avec Query Builder
	public function getNbEmplacement()
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('count(e)')->from('SYM16SimpleStockBundle:Emplacement', 'e');
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getSingleScalarResult();
	}

	// même que précédent mais avec Query Builder
	public function getNbEmplacementById($id)
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('count(e)')->from('SYM16SimpleStockBundle:Emplacement', 'e');
		$querybuilder->where('e.entrepot = :id')->setParameter('id', $id);
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getSingleScalarResult();
	}

	// même que précédent mais avec Query Builder
	public function getNbEmplacementByEntrepot($entrepot)
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('e')->from('SYM16SimpleStockBundle:Emplacement', 'e');
		//$querybuilder->leftJoin('e.entrepot', 'd')->addSelect('t');
		$querybuilder->leftJoin('e.entrepot', 't');
		$querybuilder->where('t.nom = :statut')->setParameter('statut', $entrepot);
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getResult();
	}
}
