<?php

namespace SYM16\SimpleStockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepotRepository extends EntityRepository
{
	// Nombre total d'entrerpots
	public function getNbItems()
	{
		// on crée un query builder
		$querybuilder = $this->_em->CreateQueryBuilder();
		$querybuilder->select('count(e)')->from('SYM16SimpleStockBundle:Entrepot', 'e');
		// on récuère la query à partir du quesrybuilder
		$query = $querybuilder->getQuery();
		// on l'exécute et on renvoie sa valeur	
		return $query->getSingleScalarResult();
	}

	//pour assuurer la compatibilité ascendante
	//cette fonction est obsolète
	public function getNbentrepot()
	{
		return $this->getNbItems();
	}

	// findBy en excluant un id donnée
	public function MyfindBy($attribut, $id)
	{
	    $querybuilder = $this->_em->CreateQueryBuilder();
	    $querybuilder->select('e')
		->from('SYM16SimpleStockBundle:Entrepot', 'e')
		->where('e.nom = :nom')
		->setParameter('nom', $attribut)
		->andWhere('e.id <> :id')
		->setParameter('id', $id);
	    return $querybuilder->getQuery()->getResult();
	}
}
