<?php

namespace SYM16\SimpleStockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StocklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocklistRepository extends EntityRepository
{
	// même que précédent mais avec Query Builder
	public function getNbItems()
	{
	    // on crée un query builder
	    $querybuilder = $this->_em->CreateQueryBuilder();
	    $querybuilder->select('count(s)')->from('SYM16SimpleStockBundle:Stocklist', 's');
	    // on récuère la query à partir du quesrybuilder
	    $query = $querybuilder->getQuery();
	    // on l'exécute et on renvoie sa valeur	
	    return $query->getSingleScalarResult();
	}

	// renvoie le nom d'usage du stock courant
	public function getCurrentUsage($nominterne)
	{
	    // on crée un query builder
	    $querybuilder = $this->_em->CreateQueryBuilder();
	    $querybuilder->select('s.usage')->from('SYM16SimpleStockBundle:Stocklist', 's');
	    $querybuilder->where('s.nom = :nom')->setParameter('nom', $nominterne);
	    // on récuère la query à partir du quesrybuilder
	    $query = $querybuilder->getQuery();
	    // on l'exécute et on renvoie sa valeur	
	    return $query->getSingleScalarResult();

	}
}
