<?php

namespace SYM16\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
	//renvoie le nombre total de lignes de l'entité (utilise DQL)
	public function getNbItems()
	{
		$query = $this ->_em->createQuery('
			SELECT COUNT(r)
			FROM SYM16UserBundle:Role r');
		return $query->getSingleScalarResult();
	}

	//pour assuurer la compatibilité ascendante
	//cette fonction est obsolète
	public function getNbArticle()
	{
		return $this->getNbItems();
	}

}
