sym16_simple_stock_homepage:
    path:     /hello/{name}
    defaults: { _controller: SYM16SimpleStockBundle:Default:index }

sym16_simple_stock_ilike:
    path:     /iLike/{un_verbe_a_l_infinitif}
    defaults: { _controller: SYM16SimpleStockBundle:MonPremier:iLike}
    
sym16_simple_stock_produit:
    path:     /{multiplicande}/{multiplicateur}
    defaults: { _controller: SYM16SimpleStockBundle:MonPremier:produit}
    requirements:
        multiplicande:    ^[0-9a-fA-f]*$
        multiplicateur:   ^[0-9a-fA-f]*$

sym16_simple_stock_puissance:
    path:     /puissance
    defaults: { _controller: SYM16SimpleStockBundle:MonPremier:puissance}
