services:
#    sym16_simple_stock.example:
#        class: SYM16\SimpleStockBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#
    sym16_simple_stock.lister_tout:
# la classe lister possèdera plusieurs prestations de listage
        class: SYM16\SimpleStockBundle\Services\Lister
#        arguments: [@service_id, "plain_value", %parameter%]
