services:
#    sym16_simple_stock.example:
#        class: SYM16\SimpleStockBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#
    sym16_simple_stock.lister:
        class: SYM16\SimpleStockBundle\Services\listerService
#        arguments: [@service_id, "plain_value", %parameter%]
