services:
#    sym16_simple_stock.example:
#        class: SYM16\SimpleStockBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#
#   service lister
    sym16_simple_stock.lister_tout:
#       la classe lister possèdera plusieurs prestations de listage
        class: SYM16\SimpleStockBundle\Services\ListerCorrection
#        arguments: [@service_id, "plain_value", %parameter%]
#   service vérficiation d'unicité de login (identifiant utilisateur)
    sym16_simple_stock.isunique:
        class: SYM16\SimpleStockBundle\Validator\UniqueEntityByEmValidator
        arguments: [@doctrine, @request]
        scope: request
        tags:
            - { name: validator.constraint_validator, alias: isunique } 

