imports:
    - { resource: simplestock_parameters.yml }
#    - { resource: security.yml }
#    - { resource: services.yml }

# Parameteres
parameters:
    currentstockname: %database_name%

# Assetic Configuration
assetic:
    bundles:        [SYM16SimpleStockBundle]

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            stockmaster:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name0%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            simplestock2:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name2%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:        
            default:
                connection: default
                mappings:
                    SYM16SimpleStockBundle : ~
                    SYM16UserBundle : ~
            stockmaster:
                connection: stockmaster     
                mappings:
                    SYM16SimpleStockBundle : ~
                    SYM16UserBundle : ~
            simplestock2:
                connection: simplestock2     
                mappings:
                    SYM16SimpleStockBundle : ~
                    SYM16UserBundle : ~
